# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: viclara-env
channels:
  - conda-forge
  - bioconda
  - defaults
  - hcc
dependencies:
  - conda-forge::biopython=1.78
  - conda-forge::markdown=3.3.3
  - conda-forge::pandas #=1.0.5
  - conda-forge::python=3.6.12
  - conda-forge::r-argparse=2.0.3
  - conda-forge::r-base=4.0.3
  - conda-forge::r-cowplot=1.1.0
  - conda-forge::r-data.table=1.13.4
  - conda-forge::r-dplyr=1.0.4
  - conda-forge::r-ggforce=0.3.3
  - conda-forge::r-ggplot2=3.3.2
  - conda-forge::r-gplots=3.1.1
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-hrbrthemes=0.8.0
  - conda-forge::r-markdown=1.1
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-svglite=1.2.3.2
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-viridis=0.5.1

  # required software dependencies here
  # - bioconda::abacas=1.3.1
  - bioconda::bbmap=38.87
  - bioconda::bcftools=1.10.2
  - bioconda::bedtools=2.29.2
  - bioconda::bioconductor-complexheatmap #=2.6.2         #r40_0
  - bioconda::bowtie2=2.4.2
  - bioconda::bwa=0.7.17
  - bioconda::fastp=0.20.1
  - bioconda::fastqc=0.11.9
  - bioconda::kraken2=2.1.1
  # - bioconda::mosdepth
  - bioconda::multiqc #=1.9
  # - bioconda::mummer=3.23
  - bioconda::nextflow>=20.10.0
  - bioconda::picard=2.25.1
  - bioconda::samtools=1.10
  - bioconda::snpeff=5.0
  - bioconda::snpsift=4.3.1t
  - bioconda::spades=3.14.0
  - bioconda::trimmomatic=0.39
  # - bioconda::trinity
  - bioconda::varscan=2.4.4
  
